import { AppShell } from "@/components/AppShell";

const SECTIONS = [
  {
    title: "1. Scope of these terms",
    text: "These terms describe the use of the Human AI platform (chat, accounts, memory, and related pages). They are provided as a preliminary draft and will be finalized with legal review. Nothing on this page constitutes legal advice, and no claim is made that these terms have been reviewed by a lawyer.",
  },
  {
    title: "2. Accounts",
    text: "You need an account to save chats and use personalized features. You are responsible for keeping your credentials secure and for activity under your account. Human AI may suspend accounts that abuse the service.",
  },
  {
    title: "3. Acceptable use",
    text: "Do not use Human AI for unlawful purposes, to infringe the rights of others, to generate harmful content, or to attempt to circumvent security measures, rate limits, or access controls.",
  },
  {
    title: "4. AI-generated content",
    text: "Responses are generated by third-party AI models and may be inaccurate, incomplete, or outdated. Verify important information independently. AI output is provided for general informational purposes only.",
  },
  {
    title: "5. Your content and privacy",
    text: "Messages, images, and memories you provide are stored to operate your account and are isolated per user. Do not upload sensitive personal data you do not wish to be stored. Details on retention and deletion will be specified in the finalized privacy documentation.",
  },
  {
    title: "6. Availability and changes",
    text: "Human AI is provided on an \"as is\" basis without warranties of uninterrupted availability or fitness for a particular purpose. Features, models, and limits may change as the platform evolves.",
  },
  {
    title: "7. Liability",
    text: "To the extent permitted by law, Human AI is not liable for damages arising from the use of AI-generated content or from reliance on the service. Final liability provisions will be defined during legal finalization.",
  },
  {
    title: "8. Contact and updates",
    text: "These terms are a placeholder draft and will be updated. Continued use of the platform after changes take effect constitutes acceptance of the updated terms.",
  },
];

export default function TermsPage() {
  return (
    <AppShell>
      <div className="mx-auto w-full max-w-2xl px-4 py-10 pl-14 lg:pl-4">
        <p className="text-xs font-medium uppercase tracking-widest text-accent">
          Legal
        </p>
        <h1 className="mt-2 text-2xl font-semibold tracking-tight text-white">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm leading-6 text-zinc-500">
          Draft placeholder — these terms are structured for later legal
          finalization and have not been reviewed by a lawyer.
        </p>
        <div className="mt-6 space-y-5">
          {SECTIONS.map((s) => (
            <section key={s.title} className="card p-5">
              <h2 className="text-[15px] font-semibold text-white">{s.title}</h2>
              <p className="mt-1.5 text-sm leading-6 text-zinc-400">{s.text}</p>
            </section>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
